# Custom data for person detection

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: /kaggle/input/people/train/images/
val: /kaggle/input/people/valid/images/
test: /kaggle/input/people/test/images/

nc: 1
names: ["person"]

roboflow:
    workspace: mohamed-traore-2ekkp
    project: people-detection-general
    version: 8
    license: CC BY 4.0
    url: https://universe.roboflow.com/mohamed-traore-2ekkp/people-detection-general/dataset/8
